<?xml version="1.0" encoding="UTF-8"?>
<<<<<<< HEAD
<testng-results skipped="0" failed="2" ignored="0" total="7" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="19141" started-at="2018-08-17T17:05:18Z" finished-at="2018-08-17T17:05:37Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="19141" started-at="2018-08-17T17:05:18Z" finished-at="2018-08-17T17:05:37Z">
      <class name="com.revature.test.SVPLocations">
        <test-method status="FAIL" signature="failTest()[pri:0, instance:com.revature.test.SVPLocations@7a3d45bd]" name="failTest" duration-ms="12" started-at="2018-08-17T17:05:18Z" finished-at="2018-08-17T17:05:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at com.revature.test.SVPLocations.failTest(SVPLocations.java:208)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failTest -->
        <test-method status="FAIL" signature="failTest2()[pri:0, instance:com.revature.test.SVPLocations@7a3d45bd]" name="failTest2" duration-ms="2" started-at="2018-08-17T17:05:18Z" finished-at="2018-08-17T17:05:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at com.revature.test.SVPLocations.failTest2(SVPLocations.java:214)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failTest2 -->
        <test-method status="PASS" signature="testAppLaunch()[pri:0, instance:com.revature.test.SVPLocations@7a3d45bd]" name="testAppLaunch" duration-ms="6275" started-at="2018-08-17T17:05:18Z" finished-at="2018-08-17T17:05:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAppLaunch -->
        <test-method status="PASS" signature="testLoginSVP()[pri:0, instance:com.revature.test.SVPLocations@7a3d45bd]" name="testLoginSVP" duration-ms="1433" started-at="2018-08-17T17:05:24Z" depends-on-methods="com.revature.test.SVPLocations.testAppLaunch" finished-at="2018-08-17T17:05:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginSVP -->
        <test-method status="PASS" signature="testMoveToLocationBar()[pri:0, instance:com.revature.test.SVPLocations@7a3d45bd]" name="testMoveToLocationBar" duration-ms="5811" started-at="2018-08-17T17:05:26Z" depends-on-methods="com.revature.test.SVPLocations.testLoginSVP" finished-at="2018-08-17T17:05:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMoveToLocationBar -->
        <test-method status="PASS" signature="testCloseApp()[pri:0, instance:com.revature.test.SVPLocations@7a3d45bd]" name="testCloseApp" duration-ms="2713" started-at="2018-08-17T17:05:32Z" depends-on-methods="com.revature.test.SVPLocations.testMoveToLocationBar" finished-at="2018-08-17T17:05:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCloseApp -->
        <test-method status="PASS" signature="testLaunchResults()[pri:0, instance:com.revature.test.SVPLocations@7a3d45bd]" name="testLaunchResults" duration-ms="2851" started-at="2018-08-17T17:05:34Z" depends-on-methods="com.revature.test.SVPLocations.testCloseApp" finished-at="2018-08-17T17:05:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLaunchResults -->
      </class> <!-- com.revature.test.SVPLocations -->
=======
<testng-results skipped="0" failed="0" ignored="0" total="5" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="31176" started-at="2018-08-17T18:00:58Z" finished-at="2018-08-17T18:01:30Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="31176" started-at="2018-08-17T18:00:58Z" finished-at="2018-08-17T18:01:30Z">
      <class name="com.revature.webdriver.Svp_overview">
        <test-method status="PASS" signature="testAppLaunch()[pri:0, instance:com.revature.webdriver.Svp_overview@7a3d45bd]" name="testAppLaunch" duration-ms="4500" started-at="2018-08-17T18:00:58Z" finished-at="2018-08-17T18:01:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAppLaunch -->
        <test-method status="PASS" signature="testLoginSVP()[pri:0, instance:com.revature.webdriver.Svp_overview@7a3d45bd]" name="testLoginSVP" duration-ms="2405" started-at="2018-08-17T18:01:03Z" depends-on-methods="com.revature.webdriver.Svp_overview.testAppLaunch" finished-at="2018-08-17T18:01:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginSVP -->
        <test-method status="PASS" signature="testCycleSorts()[pri:0, instance:com.revature.webdriver.Svp_overview@7a3d45bd]" name="testCycleSorts" duration-ms="22425" started-at="2018-08-17T18:01:05Z" depends-on-methods="com.revature.webdriver.Svp_overview.testLoginSVP" finished-at="2018-08-17T18:01:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCycleSorts -->
        <test-method status="PASS" signature="testCycleBatches()[pri:0, instance:com.revature.webdriver.Svp_overview@7a3d45bd]" name="testCycleBatches" duration-ms="1250" started-at="2018-08-17T18:01:28Z" depends-on-methods="com.revature.webdriver.Svp_overview.testCycleSorts" finished-at="2018-08-17T18:01:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCycleBatches -->
        <test-method status="PASS" signature="testExportCSV()[pri:0, instance:com.revature.webdriver.Svp_overview@7a3d45bd]" name="testExportCSV" duration-ms="570" started-at="2018-08-17T18:01:29Z" depends-on-methods="com.revature.webdriver.Svp_overview.testCycleBatches" finished-at="2018-08-17T18:01:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testExportCSV -->
      </class> <!-- com.revature.webdriver.Svp_overview -->
>>>>>>> origin/steve
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
